name: AES-T500
TjFree:
  - src/TjFree/aes_128.v
  - src/TjFree/round.v
  - src/TjFree/table.v
TjIn:
  - src/TjIn/top.v
  - src/TjIn/TSC.v
  - src/TjIn/aes_128.v
  - src/TjIn/round.v
  - src/TjIn/table.v
TjLoc: 
  - Tj_Trig
  - State0
  - State1
  - State2
  - State3
  - DynamicPower