name: WB_CONMAX-T200
TjFree:
  - src/TjFree/wb_conmax_arb.v
  - src/TjFree/wb_conmax_master_if.v
  - src/TjFree/wb_conmax_msel.v
  - src/TjFree/wb_conmax_pri_dec.v
  - src/TjFree/wb_conmax_pri_enc.v
  - src/TjFree/wb_conmax_rf.v
  - src/TjFree/wb_conmax_slave_if.v
  - src/TjFree/wb_conmax_top.v
TjIn:
  - src/TjIn/wb_conmax_arb.v
  - src/TjIn/wb_conmax_master_if.v
  - src/TjIn/wb_conmax_msel.v
  - src/TjIn/wb_conmax_pri_dec.v
  - src/TjIn/wb_conmax_pri_enc.v
  - src/TjIn/wb_conmax_rf.v
  - src/TjIn/wb_conmax_slave_if.v
  - src/TjIn/wb_conmax_top.v
TjLoc: 
  - Trojanstate
  - i_s15_data_o_TrojanPayload
  - i_s15_data_o
  - m0_data_o